const actionTypes = {
    LOGIN: 'LOGIN',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAIL: 'REGISTER_FAIL',
    LOGOUT: 'LOGOUT',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAIL: 'LOGIN_FAIL',
    GET_POSTS: 'GET_POSTS',
    GET_POST_BY_ID: 'GET_POST_BY_ID',
    GET_LIMIT_POSTS: 'GET_LIMIT_POSTS',
    GET_ADMIN_LIMIT_POSTS: 'GET_ADMIN_LIMIT_POSTS',
    GET_CATEGORIES: 'GET_CATEGORIES',
    GET_PRICES: 'GET_PRICES',
    GET_ACREAGE: 'GET_ACREAGE',
    GET_NEW_POST: 'GET_NEW_POST',
    GET_AREAS: 'GET_AREAS',
    EDIT_DATA: 'EDIT_DATA',
    RESET_EDIT_DATA: 'RESET_EDIT_DATA',

    //user
    GET_CURRENT_USER: 'GET_CURRENT_USER'
}

export default actionTypes